name: Analyze

on:
    workflow_call:

jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    -   language: csharp
                        builder-mode: manual
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Initialize CodeQL
                uses: github/codeql-action/init@v3
                with:
                    languages: ${{ matrix.language }}
                    build-mode: ${{ matrix.build-mode }}
            -   if: ${{ matrix.language == 'csharp' && matrix.build-mode == 'manual' }}
                run: dotnet build
            -   name: Perform CodeQL Analysis
                uses: github/codeql-action/analyze@v3
                with:
                    category: "/language:${{ matrix.language }}"
