name: Build

on:
    pull_request:
        branches: [ master ]
        paths-ignore:
            - '.github/**'
            - 'README.md'
            - 'LICENSE'

jobs:
    analyze:
        uses: ./.github/workflows/analyze.yml
    docker:
        needs: analyze
        uses: ./.github/workflows/docker.yml
        with:
            push: false
    automerge:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            -   name: Automerge
                uses: fastify/github-action-merge-dependabot@v3
                with:
                    github-token: ${{ secrets.PAT_REPO }}
                    target: minor
