name: Build

on:
    pull_request:
        branches: [ master ]
        paths-ignore:
            - '.github/**'

jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            fail-fast: false
            matrix:
                language: [ 'csharp' ]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
            -   name: Initialize CodeQL
                uses: github/codeql-action/init@v1
                with:
                    languages: ${{ matrix.language }}
            -   name: Autobuild
                uses: github/codeql-action/autobuild@v1
            -   name: Perform CodeQL Analysis
                uses: github/codeql-action/analyze@v1
    build:
        needs: analyze
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-
            -   name: Build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: false
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new
            - # Temp fix for caches are copied over the existing cache so it keeps growing currently.
                # https://github.com/docker/build-push-action/issues/252
                # https://github.com/moby/buildkit/issues/1896
                name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    automerge:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
            -   uses: fastify/github-action-merge-dependabot@v3
                with:
                    github-token: ${{ secrets.PAT_REPO }}
                    target: minor
