name: Build

on:
    pull_request:
        branches: [ master ]

jobs:
    test:
        uses: ./.github/workflows/test.yml
    automerge:
        if: ${{ github.actor == 'dependabot[bot]' }}
        needs: test
        runs-on: ubuntu-latest
        steps:
            -   name: Automerge
                uses: fastify/github-action-merge-dependabot@v3
                with:
                    github-token: ${{ secrets.PAT_REPO }}
                    target: minor
