name: Docker

on:
    workflow_call:
        inputs:
            environment:
                required: false
                type: string
        secrets:
            DOCKER_REGISTRY:
                required: false
            DOCKER_USERNAME:
                required: false
            DOCKER_PASSWORD:
                required: false
            WEBHOOK_URL:
                required: false
            WEBHOOK_SECRET:
                required: false

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-
            -   name: Login to Docker registry
                if: ${{ inputs.environment == 'production' }}
                environment: production
                uses: docker/login-action@v1
                with:
                    registry: ${{ secrets.DOCKER_REGISTRY }}
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Build
                if: ${{ inputs.environment == '' }}
                uses: docker/build-push-action@v2
                with:
                    context: ./DiscordTranslationBot
                    push: false
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new
            -   name: Build and push
                if: ${{ inputs.environment == 'production' }}
                environment: production
                uses: docker/build-push-action@v2
                with:
                    context: ./DiscordTranslationBot
                    push: true
                    tags: ${{ secrets.DOCKER_REGISTRY }}/austins/discordtranslationbot:latest
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new
            - # Temp fix for caches are copied over the existing cache so it keeps growing currently.
                # https://github.com/docker/build-push-action/issues/252
                # https://github.com/moby/buildkit/issues/1896
                name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
            -   name: Trigger deployment webhook
                if: ${{ inputs.environment == 'production' }}
                environment: production
                uses: distributhor/workflow-webhook@v2
                env:
                    webhook_url: ${{ secrets.WEBHOOK_URL }}
                    webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
                    webhook_type: "json"
                    silent: true
