name: PR

on:
    pull_request:
        branches: [ master ]

jobs:
    analyze:
        uses: ./.github/workflows/codeql.yml
    test:
        needs: analyze
        uses: ./.github/workflows/test.yml
