name: PR

on:
    pull_request:
        branches: [ main ]

jobs:
    pr-test:
        uses: ./.github/workflows/test.yml
    pr-docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v5
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build
                # Ensure Docker image builds.
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ./src/DiscordTranslationBot/Dockerfile
                    push: false
                    cache-from: type=gha,scope=pr
                    cache-to: type=gha,mode=max,scope=pr
