name: PR

on:
    pull_request_target:
        branches: [ master ]

jobs:
    analyze:
        uses: ./.github/workflows/codeql.yml
    test:
        needs: analyze
        uses: ./.github/workflows/test.yml
    automerge:
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        needs: test
        runs-on: ubuntu-latest
        steps:
            -   name: Fetch Dependabot metadata
                id: dependabot-metadata
                uses: dependabot/fetch-metadata@v1
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
            -   name: Get automerge token
                id: automerge-token
                uses: actions/create-github-app-token@v1
                with:
                    app-id: ${{ secrets.AUTOMERGE_APP_ID }}
                    private-key: ${{ secrets.AUTOMERGE_APP_PRIVATE_KEY }}
            -   name: Automerge
                if: steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
                env:
                    PR_URL: ${{ github.event.pull_request.html_url }}
                run: |
                    echo "${{ steps.automerge-token.outputs.token }}" | gh auth login --with-token
                    gh pr review --approve "$PR_URL"
                    gh pr merge --auto --merge "$PR_URL"
