name: PR

on:
    pull_request:
        branches: [ main ]

jobs:
    pr-test:
        uses: ./.github/workflows/test.yml
    pr-docker:
        needs: pr-test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Build
                # Ensure Docker image builds.
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ./src/DiscordTranslationBot/Dockerfile
                    push: false
