name: Test

on: [ workflow_call, workflow_dispatch ]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
        steps:
            -   name: Checkout
                uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            -   name: Set up .NET Core SDK
                uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
                with:
                    dotnet-version: '10.x'
            -   name: Cache NuGet packages
                uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
                with:
                    path: ${{ github.workspace }}/.nuget/packages
                    key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            -   name: Restore dependencies
                run: dotnet restore --locked-mode
            -   name: Test
                run: dotnet test --no-restore -c Release --results-directory ./test-results -- --report-ctrf
            -   if: always()
                name: Publish test report
                uses: ctrf-io/github-test-reporter@e500b992f936420eb633c91644cf10d4d71df700 # v1.1.0
                with:
                    report-path: ./test-results/*.ctrf
                    summary-report: true
                    file-report: true
                    failed-folded-report: true
                    skipped-report: true
